apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  labels:
    app: karsajobs-ui
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    tier: frontend
