version: "3.8"

services:
  item-db:
    image: mongo:3-xenial
    restart: always
    volumes:
      - app-db:/data/db
  item-app:
    build: .
    depends_on:
      - item-db
    restart: always
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
      - DB_HOST=item-db

volumes:
  app-db:
