name: Karyajobs backend pipeline
on:
  push:
    branches:
      - karsajobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: karsajobs
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.15"
      - name: Test
        run: go test -v -short --count=1 $(go list ./...)
