name: Karyajobs backend pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.15"
      - name: Test
        run: go test -v -short --count=1 $(go list ./...)
